Settings:
    APN: envizor.vzwentp # Access Point Name
    Module: BG95M3 # Module model (BG770A, BG95M3 or M95)
#    User: virtu # APN user (optional)
#    Password: virtu # APN password (optional)
#    Operator: 72410 # Carrier numeric operator code (optional)
    Mode: CATM1 # Network mode (CATM1, NBIOT or GSM) (optional)